server:
  port: 5000

app:
  email: ahmed83@me.com
  datasource:
    jdbc-url: jdbc:postgresql://localhost/webshop3d
    username: postgres
    password: password
    pool-size: 30

# AWS S3 configuration
aws:
  access_key_id: 'AKIA25AXLWROZGJI3QHL'
  secret_access_key: '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'
  s3:
    bucket: '3d-products-images'
    region: 'me-south-1'

# JWT configuration
application:
  jwt:
    secretKey: '%?ANZ!yR>%*]hV~,&k!x5z24m7Cw4+<Cc_m-/</N-8?zPLd'
    tokenPrefix: 'Bearer '
    tokenExpirationAfterDays: 14
